version: "3.2"

services:
  gateway:
    build: .
    image: hrhis-interop-gateway:latest
    env_file: .env
    ports:
      - "3213:3213"
    volumes:
      - ./secrets/private_key:/run/secrets/private_key:ro
    environment:
      PRIVATE_KEY_PATH: /run/secrets/private_key   # <-- path, not PEM text
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - dhis-network
  healthcheck:
    test: ["CMD-SHELL", "node -e \"const p=process.env.PORT||3000; require('http').get(`http://127.0.0.1:${p}/health`,r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
    interval: 30s
    timeout: 5s
    retries: 3

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  dhis-network:
    external:
      name: dhis-network
