export const PROGRAMS = {
  CHW_EMPLOYMENT: 'zyBObUsin0Q',
};

export const STAGES = {
  PAYMENT: 'KFtSY86OJ5b',
  CONTRACT: 'HmW9AEBtQnj',
  AUDIT: 'qmaIQk6gqU7',
};

export const DATA = {
  PAYMENT_CHANNEL: 'vR5EEbIO8wx',
  BANK_BIC: 'CqvVhRhKTM8',
  MNO_BIC: 'B4EfUtSyMMP',
  BANK_ACCOUNT: 'p5FAom9pPWw',
  MNO_ACCOUNT: 'OhV3SJdy7HV',
  CONTRACT_STATUS: 'saXIE3lYlsF',
  TX_STATUS: 'mSafUR4iSzA',
  TX_REASON: 'QuJ5Eno7WdP',
};

export const STATUS = { SUCCESS: 'No', FAILURE: 'Yes' };

export const MESSAGE_TYPES = {
  NEW_CHW_REGISTRATION: 'NEW_CHW_REGISTRATION',
  CHW_CONTRACT_STATUS_REQUEST: 'CHW_CONTRACT_STATUS_REQUEST',
  CHW_DEPLOYMENT: 'CHW_DEPLOYMENT',
  CHW_DUTY_POST_CHANGE: 'CHW_DUTY_POST_CHANGE',
  CHW_DEMOGRAPHIC_UPDATE: 'CHW_DEMOGRAPHIC_UPDATE',
  CHW_BANK_DETAILS_UPDATE: 'CHW_BANK_DETAILS_UPDATE',
  CHW_BANK_UPDATE_REQUEST: 'CHW_BANK_UPDATE_REQUEST',
  CHW_UPDATE_REQUEST: 'CHW_UPDATE_REQUEST',
} as const;

export const HEADER = {
  SENDER: 'HRHIS',
  RECEIVER: 'FFARS',
};
